# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0ef0411
_src_path: https://github.com/python-accelerator-middle-layer/pyaml-repository-template.git
distribution_name: pyaml-cs-oa
html_title: pyaml-cs-oa
import_name: pyaml_cs_oa
package_name: pyaml-cs-oa
repository_url: https://github.com/python-accelerator-middle-layer/pyaml-cs-oa
use_docs_extra: true
