# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 5faf13e
_src_path: https://github.com/python-accelerator-middle-layer/pyaml-repository-template.git
display_name: pyAML control system plugin for ophyd-async
package_name: pyaml_cs_oa
